---
# tasks file for ansible-flannel
- name: Create systemd drop-in directory
  file: path={{flanneld_dropin_dir}} state=directory mode=0755
  sudo: yes

- name: Set env conf
  sudo: yes
  template: src=10-env.conf dest={{flanneld_dropin_dir}}/10-env.conf
  notify:
    - Reload systemd

- name: Set peers conf
  sudo: yes
  template: src=50-network-config.conf dest={{flanneld_dropin_dir}}/50-network-config.conf
  notify:
    - Reload systemd

- name: Install flanneld unit
  sudo: yes
  command: systemctl add-wants multi-user.target {{flanneld_service}}
  register: flanneld_install
  changed_when: "'Created symlink' in flanneld_install.stdout"
  notify:
    - Reload systemd
