---
# tasks file for ansible-flannel
- name: Create systemd drop-in directory
  file: path={{flanneld_dropin_dir}} state=directory mode=0755
  sudo: yes

- name: Set env conf
  sudo: yes
  template: src=10-env.conf dest={{flanneld_dropin_dir}}/10-env.conf
  notify:
    - Reload systemd

- name: Set peers conf
  sudo: yes
  template: src=50-network-config.conf dest={{flanneld_dropin_dir}}/50-network-config.conf
  notify:
    - Reload systemd

- name: Create docker drop-in directory
  file: path={{docker_dropin_dir}} state=directory mode=0755
  sudo: yes

- name: Install flanneld unit
  sudo: yes
  template: src=40-flannel.conf dest={{docker_dropin_dir}}/40-flannel.conf
  notify:
    - Reload systemd
